// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pinboard.Models;

namespace Pinboard.Migrations
{
    [DbContext(typeof(PinboardContext))]
    [Migration("20190521150427_update-Bookmark")]
    partial class updateBookmark
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pinboard.Models.Bookmark", b =>
                {
                    b.Property<string>("BookmarkID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAndTimeCreated");

                    b.Property<string>("Description");

                    b.Property<bool>("IsReadLater");

                    b.Property<bool>("IsStarred");

                    b.Property<bool>("IsTagged");

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("BookmarkID");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Pinboard.Models.User", b =>
                {
                    b.Property<string>("EmailID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Password");

                    b.Property<string>("UserHandle");

                    b.HasKey("EmailID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
